/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface HostingPlan {
  'id' : string,
  'fps' : bigint,
  'ram' : bigint,
  'name' : string,
  'price' : bigint,
}
export interface MinecraftServer {
  'id' : string,
  'status' : string,
  'domain' : string,
  'owner' : Principal,
  'createdAt' : Time,
  'plan' : HostingPlan,
  'installedPlugins' : Array<string>,
}
export interface PaymentRecord {
  'id' : string,
  'status' : string,
  'planId' : string,
  'user' : Principal,
  'timestamp' : Time,
  'stripeSessionId' : string,
  'amount' : bigint,
}
export interface Plugin {
  'id' : string,
  'url' : string,
  'name' : string,
  'description' : string,
  'version' : string,
}
export interface ServerPermission {
  'grantedAt' : Time,
  'grantedBy' : Principal,
  'user' : Principal,
  'canExecuteCommands' : boolean,
  'serverId' : string,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addPlan' : ActorMethod<[HostingPlan], undefined>,
  'addPlugin' : ActorMethod<[Plugin], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createServer' : ActorMethod<[string], MinecraftServer>,
  'getAllPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getAllServers' : ActorMethod<[], Array<MinecraftServer>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyPayments' : ActorMethod<[], Array<PaymentRecord>>,
  'getMyServers' : ActorMethod<[], Array<MinecraftServer>>,
  'getPlans' : ActorMethod<[], Array<HostingPlan>>,
  'getPlugins' : ActorMethod<[], Array<Plugin>>,
  'getServer' : ActorMethod<[string], [] | [MinecraftServer]>,
  'getServerPermissions' : ActorMethod<[string], Array<ServerPermission>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantServerPermission' : ActorMethod<
    [string, Principal, boolean],
    undefined
  >,
  'installPluginToServer' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'processStripePayment' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'recordPayment' : ActorMethod<[string, bigint, string], undefined>,
  'removePluginFromServer' : ActorMethod<[string, string], undefined>,
  'revokeServerPermission' : ActorMethod<[string, Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateServerStatus' : ActorMethod<[string, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];