/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const HostingPlan = IDL.Record({
  'id' : IDL.Text,
  'fps' : IDL.Nat,
  'ram' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
});
export const Plugin = IDL.Record({
  'id' : IDL.Text,
  'url' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'version' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Time = IDL.Int;
export const MinecraftServer = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'domain' : IDL.Text,
  'owner' : IDL.Principal,
  'createdAt' : Time,
  'plan' : HostingPlan,
  'installedPlugins' : IDL.Vec(IDL.Text),
});
export const PaymentRecord = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'planId' : IDL.Text,
  'user' : IDL.Principal,
  'timestamp' : Time,
  'stripeSessionId' : IDL.Text,
  'amount' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ServerPermission = IDL.Record({
  'grantedAt' : Time,
  'grantedBy' : IDL.Principal,
  'user' : IDL.Principal,
  'canExecuteCommands' : IDL.Bool,
  'serverId' : IDL.Text,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPlan' : IDL.Func([HostingPlan], [], []),
  'addPlugin' : IDL.Func([Plugin], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createServer' : IDL.Func([IDL.Text], [MinecraftServer], []),
  'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getAllServers' : IDL.Func([], [IDL.Vec(MinecraftServer)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
  'getMyServers' : IDL.Func([], [IDL.Vec(MinecraftServer)], ['query']),
  'getPlans' : IDL.Func([], [IDL.Vec(HostingPlan)], ['query']),
  'getPlugins' : IDL.Func([], [IDL.Vec(Plugin)], ['query']),
  'getServer' : IDL.Func([IDL.Text], [IDL.Opt(MinecraftServer)], ['query']),
  'getServerPermissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ServerPermission)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantServerPermission' : IDL.Func(
      [IDL.Text, IDL.Principal, IDL.Bool],
      [],
      [],
    ),
  'installPluginToServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'processStripePayment' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'recordPayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
  'removePluginFromServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'revokeServerPermission' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateServerStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const HostingPlan = IDL.Record({
    'id' : IDL.Text,
    'fps' : IDL.Nat,
    'ram' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
  });
  const Plugin = IDL.Record({
    'id' : IDL.Text,
    'url' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'version' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Time = IDL.Int;
  const MinecraftServer = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'domain' : IDL.Text,
    'owner' : IDL.Principal,
    'createdAt' : Time,
    'plan' : HostingPlan,
    'installedPlugins' : IDL.Vec(IDL.Text),
  });
  const PaymentRecord = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'planId' : IDL.Text,
    'user' : IDL.Principal,
    'timestamp' : Time,
    'stripeSessionId' : IDL.Text,
    'amount' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ServerPermission = IDL.Record({
    'grantedAt' : Time,
    'grantedBy' : IDL.Principal,
    'user' : IDL.Principal,
    'canExecuteCommands' : IDL.Bool,
    'serverId' : IDL.Text,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPlan' : IDL.Func([HostingPlan], [], []),
    'addPlugin' : IDL.Func([Plugin], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createServer' : IDL.Func([IDL.Text], [MinecraftServer], []),
    'getAllPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getAllServers' : IDL.Func([], [IDL.Vec(MinecraftServer)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyPayments' : IDL.Func([], [IDL.Vec(PaymentRecord)], ['query']),
    'getMyServers' : IDL.Func([], [IDL.Vec(MinecraftServer)], ['query']),
    'getPlans' : IDL.Func([], [IDL.Vec(HostingPlan)], ['query']),
    'getPlugins' : IDL.Func([], [IDL.Vec(Plugin)], ['query']),
    'getServer' : IDL.Func([IDL.Text], [IDL.Opt(MinecraftServer)], ['query']),
    'getServerPermissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ServerPermission)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantServerPermission' : IDL.Func(
        [IDL.Text, IDL.Principal, IDL.Bool],
        [],
        [],
      ),
    'installPluginToServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'processStripePayment' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'recordPayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [], []),
    'removePluginFromServer' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'revokeServerPermission' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateServerStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };